/**
 * MonoBlocks — api/seed.ts
 *
 * Seed data for the mock backend. Port of prototype data.js seed().
 * All entity records + events for the Cornerstone Property Services demo.
 */

import type { DataStore } from '@/schema/types.ts';

export const SEED_VERSION = 3;

export function seed(): DataStore {
  return {
    version: SEED_VERSION,
    customers: [
      {
        id: 'cust-001',
        entity_type: 'customer',
        name: 'Harborview Realty Trust',
        billing_email: 'ap@harborviewrealty.example',
        phone: '(206) 555-0101',
        tier: 'enterprise',
        status: 'active',
        contract_start: '2021-03-01',
      },
      {
        id: 'cust-002',
        entity_type: 'customer',
        name: 'Maple Court Residential',
        billing_email: 'billing@maplecourt.example',
        phone: '(503) 555-0102',
        tier: 'premium',
        status: 'active',
        contract_start: '2022-06-15',
      },
      {
        id: 'cust-003',
        entity_type: 'customer',
        name: 'Ironwood Industrial Park',
        billing_email: 'accounts@ironwoodind.example',
        phone: '(253) 555-0103',
        tier: 'enterprise',
        status: 'active',
        contract_start: '2019-11-01',
      },
      {
        id: 'cust-004',
        entity_type: 'customer',
        name: 'Bella Vita Restaurants',
        billing_email: 'ops@bellavitagroup.example',
        phone: '(206) 555-0104',
        tier: 'standard',
        status: 'active',
        contract_start: '2023-01-10',
      },
      {
        id: 'cust-005',
        entity_type: 'customer',
        name: 'Northgate Medical Plaza',
        billing_email: 'facilities@northgatemed.example',
        phone: '(206) 555-0105',
        tier: 'premium',
        status: 'active',
        contract_start: '2020-09-01',
      },
      {
        id: 'cust-006',
        entity_type: 'customer',
        name: 'Sunset Strip Retail Group',
        billing_email: 'pay@sunsetstrip.example',
        phone: '(971) 555-0106',
        tier: 'standard',
        status: 'inactive',
        contract_start: '2018-04-20',
      },
      {
        id: 'cust-007',
        entity_type: 'customer',
        name: 'Cascade Logistics',
        billing_email: 'fm@cascadelogistics.example',
        phone: '(425) 555-0107',
        tier: 'enterprise',
        status: 'prospective',
        contract_start: '',
      },
      {
        id: 'cust-008',
        entity_type: 'customer',
        name: 'Elm & Vine Hotels',
        billing_email: 'engineering@elmvine.example',
        phone: '(503) 555-0108',
        tier: 'premium',
        status: 'active',
        contract_start: '2024-02-01',
      },
    ],
    sites: [
      {
        id: 'site-001',
        entity_type: 'site',
        name: 'Harborview Tower',
        customer_id: 'cust-001',
        address: '1200 Harbor Ave',
        city: 'Seattle',
        site_type: 'commercial',
        square_footage: 285000,
        status: 'active',
      },
      {
        id: 'site-002',
        entity_type: 'site',
        name: 'Harborview Annex',
        customer_id: 'cust-001',
        address: '1240 Harbor Ave',
        city: 'Seattle',
        site_type: 'commercial',
        square_footage: 96000,
        status: 'active',
      },
      {
        id: 'site-003',
        entity_type: 'site',
        name: 'Maple Court Apartments',
        customer_id: 'cust-002',
        address: '455 Maple St',
        city: 'Portland',
        site_type: 'residential',
        square_footage: 142000,
        status: 'active',
      },
      {
        id: 'site-004',
        entity_type: 'site',
        name: 'Maple Court Townhomes',
        customer_id: 'cust-002',
        address: '480 Maple St',
        city: 'Portland',
        site_type: 'residential',
        square_footage: 68000,
        status: 'active',
      },
      {
        id: 'site-005',
        entity_type: 'site',
        name: 'Ironwood Building A',
        customer_id: 'cust-003',
        address: '9000 Ironwood Pkwy',
        city: 'Tacoma',
        site_type: 'commercial',
        square_footage: 210000,
        status: 'active',
      },
      {
        id: 'site-006',
        entity_type: 'site',
        name: 'Ironwood Warehouse 3',
        customer_id: 'cust-003',
        address: '9040 Ironwood Pkwy',
        city: 'Tacoma',
        site_type: 'commercial',
        square_footage: 155000,
        status: 'active',
      },
      {
        id: 'site-007',
        entity_type: 'site',
        name: 'Bella Vita Downtown',
        customer_id: 'cust-004',
        address: '310 Main St',
        city: 'Seattle',
        site_type: 'retail',
        square_footage: 4800,
        status: 'active',
      },
      {
        id: 'site-008',
        entity_type: 'site',
        name: 'Bella Vita Waterfront',
        customer_id: 'cust-004',
        address: '77 Pier Walk',
        city: 'Seattle',
        site_type: 'retail',
        square_footage: 6200,
        status: 'active',
      },
      {
        id: 'site-009',
        entity_type: 'site',
        name: 'Northgate Medical Plaza',
        customer_id: 'cust-005',
        address: '1500 Northgate Way',
        city: 'Seattle',
        site_type: 'commercial',
        square_footage: 120000,
        status: 'active',
      },
      {
        id: 'site-010',
        entity_type: 'site',
        name: 'Northgate Imaging Center',
        customer_id: 'cust-005',
        address: '1520 Northgate Way',
        city: 'Seattle',
        site_type: 'commercial',
        square_footage: 32000,
        status: 'active',
      },
      {
        id: 'site-011',
        entity_type: 'site',
        name: 'Sunset Market Hall',
        customer_id: 'cust-006',
        address: '2200 Sunset Blvd',
        city: 'Portland',
        site_type: 'retail',
        square_footage: 28000,
        status: 'inactive',
      },
      {
        id: 'site-012',
        entity_type: 'site',
        name: 'Sunset Crossing',
        customer_id: 'cust-006',
        address: '2350 Sunset Blvd',
        city: 'Portland',
        site_type: 'retail',
        square_footage: 41000,
        status: 'inactive',
      },
      {
        id: 'site-013',
        entity_type: 'site',
        name: 'Cascade Distribution Hub',
        customer_id: 'cust-007',
        address: '800 Cascade Way',
        city: 'Kent',
        site_type: 'commercial',
        square_footage: 340000,
        status: 'active',
      },
      {
        id: 'site-014',
        entity_type: 'site',
        name: 'Elm & Vine Grand Hotel',
        customer_id: 'cust-008',
        address: '400 Vine St',
        city: 'Portland',
        site_type: 'commercial',
        square_footage: 188000,
        status: 'active',
      },
    ],
    equipment: [
      {
        id: 'equip-001',
        entity_type: 'equipment',
        serial_number: 'HVAC-CPS-1001',
        equipment_type: 'hvac',
        site_id: 'site-001',
        location: 'Rooftop, north mechanical deck',
        install_date: '2019-04-12',
        last_service_date: '2026-06-18',
        status: 'operational',
      },
      {
        id: 'equip-002',
        entity_type: 'equipment',
        serial_number: 'HVAC-CPS-1002',
        equipment_type: 'hvac',
        site_id: 'site-001',
        location: 'Rooftop, south mechanical deck',
        install_date: '2019-04-12',
        last_service_date: '2026-05-02',
        status: 'operational',
      },
      {
        id: 'equip-003',
        entity_type: 'equipment',
        serial_number: 'ELV-CPS-2101',
        equipment_type: 'elevator',
        site_id: 'site-001',
        location: 'Core bank A, floors 1–24',
        install_date: '2018-09-30',
        last_service_date: '2026-08-21',
        status: 'operational',
      },
      {
        id: 'equip-004',
        entity_type: 'equipment',
        serial_number: 'ELV-CPS-2102',
        equipment_type: 'elevator',
        site_id: 'site-001',
        location: 'Freight shaft, loading level',
        install_date: '2018-09-30',
        last_service_date: '2026-03-14',
        status: 'maintenance',
      },
      {
        id: 'equip-005',
        entity_type: 'equipment',
        serial_number: 'BLR-CPS-3101',
        equipment_type: 'boiler',
        site_id: 'site-002',
        location: 'Basement plant room',
        install_date: '2020-11-05',
        last_service_date: '2026-07-09',
        status: 'operational',
      },
      {
        id: 'equip-006',
        entity_type: 'equipment',
        serial_number: 'PMP-CPS-4101',
        equipment_type: 'pump',
        site_id: 'site-002',
        location: 'Utility closet, level P1',
        install_date: '2021-02-19',
        last_service_date: '2026-01-22',
        status: 'down',
      },
      {
        id: 'equip-007',
        entity_type: 'equipment',
        serial_number: 'HVAC-CPS-1103',
        equipment_type: 'hvac',
        site_id: 'site-003',
        location: 'Rooftop, building C',
        install_date: '2020-06-01',
        last_service_date: '2026-06-30',
        status: 'operational',
      },
      {
        id: 'equip-008',
        entity_type: 'equipment',
        serial_number: 'BLR-CPS-3102',
        equipment_type: 'boiler',
        site_id: 'site-003',
        location: 'Central plant, courtyard',
        install_date: '2019-10-15',
        last_service_date: '2026-02-11',
        status: 'operational',
      },
      {
        id: 'equip-009',
        entity_type: 'equipment',
        serial_number: 'PMP-CPS-4102',
        equipment_type: 'pump',
        site_id: 'site-004',
        location: 'Pump house, east lot',
        install_date: '2021-08-24',
        last_service_date: '2025-11-30',
        status: 'operational',
      },
      {
        id: 'equip-010',
        entity_type: 'equipment',
        serial_number: 'GEN-CPS-5101',
        equipment_type: 'generator',
        site_id: 'site-005',
        location: 'Yard pad, east fence line',
        install_date: '2017-05-08',
        last_service_date: '2026-08-02',
        status: 'operational',
      },
      {
        id: 'equip-011',
        entity_type: 'equipment',
        serial_number: 'HVAC-CPS-1104',
        equipment_type: 'hvac',
        site_id: 'site-005',
        location: 'Rooftop, east wing',
        install_date: '2018-03-22',
        last_service_date: '2026-04-17',
        status: 'maintenance',
      },
      {
        id: 'equip-012',
        entity_type: 'equipment',
        serial_number: 'PMP-CPS-4103',
        equipment_type: 'pump',
        site_id: 'site-006',
        location: 'Fire suppression room',
        install_date: '2019-07-11',
        last_service_date: '2026-05-28',
        status: 'operational',
      },
      {
        id: 'equip-013',
        entity_type: 'equipment',
        serial_number: 'GEN-CPS-5102',
        equipment_type: 'generator',
        site_id: 'site-006',
        location: 'Dock-side enclosure',
        install_date: '2020-01-30',
        last_service_date: '2025-12-19',
        status: 'down',
      },
      {
        id: 'equip-014',
        entity_type: 'equipment',
        serial_number: 'HVAC-CPS-1105',
        equipment_type: 'hvac',
        site_id: 'site-007',
        location: 'Kitchen roof, grease-duct riser',
        install_date: '2022-03-14',
        last_service_date: '2026-09-03',
        status: 'operational',
      },
      {
        id: 'equip-015',
        entity_type: 'equipment',
        serial_number: 'HVAC-CPS-1106',
        equipment_type: 'hvac',
        site_id: 'site-008',
        location: 'Rooftop, patio level',
        install_date: '2021-05-20',
        last_service_date: '2026-07-25',
        status: 'operational',
      },
      {
        id: 'equip-016',
        entity_type: 'equipment',
        serial_number: 'ELV-CPS-2103',
        equipment_type: 'elevator',
        site_id: 'site-009',
        location: 'Main bank, floors 1–8',
        install_date: '2016-11-09',
        last_service_date: '2026-08-14',
        status: 'operational',
      },
      {
        id: 'equip-017',
        entity_type: 'equipment',
        serial_number: 'BLR-CPS-3103',
        equipment_type: 'boiler',
        site_id: 'site-009',
        location: 'Sublevel plant room',
        install_date: '2016-11-09',
        last_service_date: '2026-01-08',
        status: 'operational',
      },
      {
        id: 'equip-018',
        entity_type: 'equipment',
        serial_number: 'GEN-CPS-5103',
        equipment_type: 'generator',
        site_id: 'site-010',
        location: 'Rear lot, imaging wing',
        install_date: '2018-06-27',
        last_service_date: '2026-06-05',
        status: 'operational',
      },
      {
        id: 'equip-019',
        entity_type: 'equipment',
        serial_number: 'HVAC-CPS-1107',
        equipment_type: 'hvac',
        site_id: 'site-013',
        location: 'Roof, dock 4 zone',
        install_date: '2015-09-16',
        last_service_date: '2026-03-30',
        status: 'operational',
      },
      {
        id: 'equip-020',
        entity_type: 'equipment',
        serial_number: 'ELV-CPS-2104',
        equipment_type: 'elevator',
        site_id: 'site-014',
        location: 'Grand bank, floors 1–18',
        install_date: '2014-04-02',
        last_service_date: '2026-08-30',
        status: 'maintenance',
      },
    ],
    technicians: [
      {
        id: 'tech-001',
        entity_type: 'technician',
        name: 'Marcus Webb',
        email: 'marcus.webb@cornerstoneps.example',
        phone: '(206) 555-0142',
        skills: ['hvac', 'boiler', 'generator'],
        certification_level: 'master',
        status: 'available',
      },
      {
        id: 'tech-002',
        entity_type: 'technician',
        name: 'Priya Raman',
        email: 'priya.raman@cornerstoneps.example',
        phone: '(503) 555-0117',
        skills: ['elevator', 'electrical'],
        certification_level: 'III',
        status: 'on_job',
      },
      {
        id: 'tech-003',
        entity_type: 'technician',
        name: 'Dana Whitfield',
        email: 'dana.whitfield@cornerstoneps.example',
        phone: '(253) 555-0164',
        skills: ['plumbing', 'fire_safety', 'hvac'],
        certification_level: 'II',
        status: 'available',
      },
      {
        id: 'tech-004',
        entity_type: 'technician',
        name: 'Luis Herrera',
        email: 'luis.herrera@cornerstoneps.example',
        phone: '(206) 555-0188',
        skills: ['hvac', 'electrical', 'generator'],
        certification_level: 'III',
        status: 'on_job',
      },
      {
        id: 'tech-005',
        entity_type: 'technician',
        name: 'Aisha Thompson',
        email: 'aisha.thompson@cornerstoneps.example',
        phone: '(971) 555-0129',
        skills: ['elevator', 'fire_safety'],
        certification_level: 'master',
        status: 'off',
      },
      {
        id: 'tech-006',
        entity_type: 'technician',
        name: 'Ken Nakamura',
        email: 'ken.nakamura@cornerstoneps.example',
        phone: '(425) 555-0173',
        skills: ['boiler', 'plumbing', 'hvac'],
        certification_level: 'II',
        status: 'available',
      },
    ],
    work_orders: [
      {
        id: 'wo-001',
        entity_type: 'work_order',
        title: 'Quarterly rooftop HVAC inspection',
        site_id: 'site-001',
        technician_id: 'tech-001',
        priority: 'normal',
        status: 'scheduled',
        scheduled_for: '2026-09-18',
        location: 'Rooftop, north mechanical deck',
        notes: 'Filter check and belt tension on both rooftop units. Access via service elevator.',
      },
      {
        id: 'wo-002',
        entity_type: 'work_order',
        title: 'Freight elevator door sensor fault',
        site_id: 'site-001',
        technician_id: 'tech-002',
        priority: 'urgent',
        status: 'in_progress',
        scheduled_for: '2026-09-14',
        location: 'Freight shaft, loading level',
        notes:
          'Doors failing to close at level P2. Sensor replacement in progress; car out of service until parts arrive.',
      },
      {
        id: 'wo-003',
        entity_type: 'work_order',
        title: 'Boiler pressure relief valve replacement',
        site_id: 'site-002',
        technician_id: 'tech-003',
        priority: 'high',
        status: 'scheduled',
        scheduled_for: '2026-09-16',
        location: 'Basement plant room',
        notes: 'Relief valve weeping at 90 psi. Replacement valve staged in the shop.',
      },
      {
        id: 'wo-004',
        entity_type: 'work_order',
        title: 'Restore domestic water pump',
        site_id: 'site-002',
        technician_id: 'tech-003',
        priority: 'urgent',
        status: 'open',
        scheduled_for: '2026-09-15',
        location: 'Utility closet, level P1',
        notes:
          'Pump PMP-CPS-4101 down since Sep 12; building on temporary feed. Motor winding suspected.',
      },
      {
        id: 'wo-005',
        entity_type: 'work_order',
        title: 'Fall heating readiness check',
        site_id: 'site-003',
        technician_id: 'tech-006',
        priority: 'normal',
        status: 'scheduled',
        scheduled_for: '2026-09-25',
        location: 'Central plant, courtyard',
        notes:
          'Pre-season boiler start-up, expansion tank pressure, and zone valve sweep across buildings A–C.',
      },
      {
        id: 'wo-006',
        entity_type: 'work_order',
        title: 'Grease duct fan service',
        site_id: 'site-007',
        technician_id: 'tech-004',
        priority: 'low',
        status: 'completed',
        scheduled_for: '2026-09-05',
        location: 'Kitchen roof, grease-duct riser',
        notes: 'Completed. Fan bearings repacked, duct interior degreased, make-up air balanced.',
      },
      {
        id: 'wo-007',
        entity_type: 'work_order',
        title: 'Patio HVAC thermostat recalibration',
        site_id: 'site-008',
        technician_id: 'tech-004',
        priority: 'normal',
        status: 'completed',
        scheduled_for: '2026-09-02',
        location: 'Rooftop, patio level',
        notes:
          'Completed. Thermostat reading 3°F high; recalibrated and verified against reference probe.',
      },
      {
        id: 'wo-008',
        entity_type: 'work_order',
        title: 'Generator load bank test',
        site_id: 'site-005',
        technician_id: 'tech-001',
        priority: 'high',
        status: 'scheduled',
        scheduled_for: '2026-09-22',
        location: 'Yard pad, east fence line',
        notes: 'Annual 4-hour load bank test. Coordinate fuel delivery for the week prior.',
      },
      {
        id: 'wo-009',
        entity_type: 'work_order',
        title: 'Warehouse dock door seal repair',
        site_id: 'site-006',
        technician_id: '',
        priority: 'normal',
        status: 'open',
        scheduled_for: '2026-09-24',
        location: 'Dock 2, west wall',
        notes: 'Dock seal torn by forklift. Awaiting assignment; parts on order.',
      },
      {
        id: 'wo-010',
        entity_type: 'work_order',
        title: 'Fire pump controller fuse replacement',
        site_id: 'site-006',
        technician_id: 'tech-003',
        priority: 'urgent',
        status: 'completed',
        scheduled_for: '2026-09-08',
        location: 'Fire suppression room',
        notes:
          'Completed. Controller fuse blown after storm; replaced and pump run-tested on jockey cycle.',
      },
      {
        id: 'wo-011',
        entity_type: 'work_order',
        title: 'Restore yard generator',
        site_id: 'site-006',
        technician_id: 'tech-001',
        priority: 'high',
        status: 'in_progress',
        scheduled_for: '2026-09-14',
        location: 'Dock-side enclosure',
        notes:
          'GEN-CPS-5102 failed to start on monthly exercise. Starter solenoid being replaced; coolant flush next.',
      },
      {
        id: 'wo-012',
        entity_type: 'work_order',
        title: 'Imaging suite UPS battery check',
        site_id: 'site-010',
        technician_id: 'tech-002',
        priority: 'normal',
        status: 'scheduled',
        scheduled_for: '2026-09-29',
        location: 'Rear lot, imaging wing',
        notes:
          'Quarterly battery impedance test on the imaging UPS. Tenant must be notified 48h ahead.',
      },
      {
        id: 'wo-013',
        entity_type: 'work_order',
        title: 'Elevator annual certification prep',
        site_id: 'site-009',
        technician_id: 'tech-005',
        priority: 'high',
        status: 'scheduled',
        scheduled_for: '2026-10-06',
        location: 'Main bank, floors 1–8',
        notes:
          'Pre-inspection ahead of the state certification visit. Safety edge and governor test on both cars.',
      },
      {
        id: 'wo-014',
        entity_type: 'work_order',
        title: 'Boiler water treatment flush',
        site_id: 'site-009',
        technician_id: '',
        priority: 'low',
        status: 'open',
        scheduled_for: '2026-10-12',
        location: 'Sublevel plant room',
        notes:
          'Blowdown and chemical treatment flush; conductivity trending high on last two readings.',
      },
      {
        id: 'wo-015',
        entity_type: 'work_order',
        title: 'Dock 4 HVAC belt replacement',
        site_id: 'site-013',
        technician_id: 'tech-006',
        priority: 'normal',
        status: 'cancelled',
        scheduled_for: '2026-09-10',
        location: 'Roof, dock 4 zone',
        notes: 'Cancelled — tenant rescheduled to the Q4 fit-out window.',
      },
    ],
    events: [
      {
        id: 'evt-001',
        entity_type: 'work_order',
        entity_id: 'wo-002',
        event_type: 'status_changed',
        payload: { from: 'scheduled', to: 'in_progress' },
        timestamp: '2026-09-14T08:12:00.000Z',
      },
      {
        id: 'evt-002',
        entity_type: 'work_order',
        entity_id: 'wo-002',
        event_type: 'assigned',
        payload: { technician_id: 'tech-002' },
        timestamp: '2026-09-13T16:40:00.000Z',
      },
      {
        id: 'evt-003',
        entity_type: 'work_order',
        entity_id: 'wo-002',
        event_type: 'note_added',
        payload: { note: 'Car taken out of service; sensor ordered overnight.' },
        timestamp: '2026-09-14T09:05:00.000Z',
      },
      {
        id: 'evt-004',
        entity_type: 'work_order',
        entity_id: 'wo-004',
        event_type: 'status_changed',
        payload: { from: null, to: 'open' },
        timestamp: '2026-09-12T14:22:00.000Z',
      },
      {
        id: 'evt-005',
        entity_type: 'work_order',
        entity_id: 'wo-011',
        event_type: 'status_changed',
        payload: { from: 'open', to: 'in_progress' },
        timestamp: '2026-09-14T07:45:00.000Z',
      },
      {
        id: 'evt-006',
        entity_type: 'work_order',
        entity_id: 'wo-010',
        event_type: 'status_changed',
        payload: { from: 'in_progress', to: 'completed' },
        timestamp: '2026-09-08T17:30:00.000Z',
      },
      {
        id: 'evt-007',
        entity_type: 'work_order',
        entity_id: 'wo-015',
        event_type: 'status_changed',
        payload: { from: 'scheduled', to: 'cancelled' },
        timestamp: '2026-09-09T11:02:00.000Z',
      },
      {
        id: 'evt-008',
        entity_type: 'work_order',
        entity_id: 'wo-006',
        event_type: 'status_changed',
        payload: { from: 'in_progress', to: 'completed' },
        timestamp: '2026-09-05T15:10:00.000Z',
      },
      {
        id: 'evt-009',
        entity_type: 'work_order',
        entity_id: 'wo-007',
        event_type: 'status_changed',
        payload: { from: 'in_progress', to: 'completed' },
        timestamp: '2026-09-02T13:55:00.000Z',
      },
      {
        id: 'evt-010',
        entity_type: 'technician',
        entity_id: 'tech-002',
        event_type: 'checked_in',
        payload: { site_id: 'site-001' },
        timestamp: '2026-09-14T07:58:00.000Z',
      },
      {
        id: 'evt-011',
        entity_type: 'technician',
        entity_id: 'tech-001',
        event_type: 'checked_in',
        payload: { site_id: 'site-006' },
        timestamp: '2026-09-14T07:31:00.000Z',
      },
      {
        id: 'evt-012',
        entity_type: 'technician',
        entity_id: 'tech-005',
        event_type: 'certification_renewed',
        payload: { certification_level: 'master' },
        timestamp: '2026-08-01T09:00:00.000Z',
      },
      {
        id: 'evt-013',
        entity_type: 'technician',
        entity_id: 'tech-003',
        event_type: 'checked_in',
        payload: { site_id: 'site-006' },
        timestamp: '2026-09-08T08:04:00.000Z',
      },
      {
        id: 'evt-014',
        entity_type: 'equipment',
        entity_id: 'equip-004',
        event_type: 'fault_reported',
        payload: { fault: 'Door sensor intermittent at level P2' },
        timestamp: '2026-09-13T15:20:00.000Z',
      },
      {
        id: 'evt-015',
        entity_type: 'equipment',
        entity_id: 'equip-006',
        event_type: 'fault_reported',
        payload: { fault: 'Motor stalled; thermal trip on restart' },
        timestamp: '2026-09-12T13:48:00.000Z',
      },
      {
        id: 'evt-016',
        entity_type: 'equipment',
        entity_id: 'equip-013',
        event_type: 'fault_reported',
        payload: { fault: 'Failed to crank on monthly exercise' },
        timestamp: '2026-09-11T10:15:00.000Z',
      },
      {
        id: 'evt-017',
        entity_type: 'equipment',
        entity_id: 'equip-001',
        event_type: 'service_completed',
        payload: { work_order_id: 'wo-001', note: 'Pre-visit filter order confirmed' },
        timestamp: '2026-06-18T16:00:00.000Z',
      },
      {
        id: 'evt-018',
        entity_type: 'equipment',
        entity_id: 'equip-017',
        event_type: 'reading_recorded',
        payload: { metric: 'conductivity', value: '4100 ppm' },
        timestamp: '2026-09-10T09:30:00.000Z',
      },
      {
        id: 'evt-019',
        entity_type: 'equipment',
        entity_id: 'equip-008',
        event_type: 'service_completed',
        payload: { note: 'Burner nozzle replaced, combustion tuned' },
        timestamp: '2026-02-11T14:10:00.000Z',
      },
      {
        id: 'evt-020',
        entity_type: 'equipment',
        entity_id: 'equip-020',
        event_type: 'reading_recorded',
        payload: { metric: 'door cycle time', value: '4.2 s' },
        timestamp: '2026-08-30T11:45:00.000Z',
      },
      {
        id: 'evt-021',
        entity_type: 'site',
        entity_id: 'site-001',
        event_type: 'inspection_completed',
        payload: { scope: 'Annual life-safety walk', result: 'Passed with 1 advisory' },
        timestamp: '2026-08-28T15:00:00.000Z',
      },
      {
        id: 'evt-022',
        entity_type: 'site',
        entity_id: 'site-009',
        event_type: 'inspection_completed',
        payload: { scope: 'Medical tenant quarterly walk', result: 'Passed' },
        timestamp: '2026-07-19T13:20:00.000Z',
      },
      {
        id: 'evt-023',
        entity_type: 'site',
        entity_id: 'site-006',
        event_type: 'inspection_completed',
        payload: { scope: 'Post-storm roof and yard check', result: 'Generator fault logged' },
        timestamp: '2026-09-11T10:40:00.000Z',
      },
      {
        id: 'evt-024',
        entity_type: 'customer',
        entity_id: 'cust-008',
        event_type: 'contract_renewed',
        payload: { term: '24 months' },
        timestamp: '2026-02-01T09:00:00.000Z',
      },
      {
        id: 'evt-025',
        entity_type: 'customer',
        entity_id: 'cust-002',
        event_type: 'tier_changed',
        payload: { from: 'standard', to: 'premium' },
        timestamp: '2026-06-15T09:00:00.000Z',
      },
      {
        id: 'evt-026',
        entity_type: 'customer',
        entity_id: 'cust-006',
        event_type: 'contract_renewed',
        payload: { note: 'Contract lapsed — account moved to inactive' },
        timestamp: '2026-04-20T09:00:00.000Z',
      },
      {
        id: 'evt-027',
        entity_type: 'customer',
        entity_id: 'cust-007',
        event_type: 'tier_changed',
        payload: { from: null, to: 'enterprise', note: 'Prospect scoping the Kent hub' },
        timestamp: '2026-08-15T09:00:00.000Z',
      },
    ],
  };
}
