package io.github.paulushcgcj.roadtoarch.spat.service;

import io.github.paulushcgcj.roadtoarch.spat.dto.EntityDetailView;
import io.github.paulushcgcj.roadtoarch.spat.dto.EntityRelationshipView;
import io.github.paulushcgcj.roadtoarch.spat.dto.EntitySummary;
import io.github.paulushcgcj.roadtoarch.spat.dto.EntityView;
import io.github.paulushcgcj.roadtoarch.spat.dto.EntityWriteRequest;
import io.github.paulushcgcj.roadtoarch.spat.dto.EventView;
import io.github.paulushcgcj.roadtoarch.spat.dto.LocationDto;
import io.github.paulushcgcj.roadtoarch.spat.dto.RelationshipView;
import io.github.paulushcgcj.roadtoarch.spat.entity.EntityRecord;
import io.github.paulushcgcj.roadtoarch.spat.entity.Event;
import io.github.paulushcgcj.roadtoarch.spat.entity.Relationship;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.locationtech.jts.geom.Point;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Component;
import org.mapstruct.AfterMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

/**
 * Translates between the generic persistence model and the wire DTOs.
 *
 * <p>All structural mapping is generated by MapStruct. Business rules live in hand-written {@code
 * default} methods or in the static helpers of {@link io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil}.
 */
@Component
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface EntityMapper extends RelationshipMapper, EventMapper {

  // ── entity → read models ──────────────────────────────────────

  /** EntityRecord → EntityView with flattened attributes baked in. */
  @Mapping(target = "attributes",
      expression = "java(new LinkedHashMap<>(entity.getAttributes()))")
  @AfterMapping
  default void enrichFlattened(@MappingTarget EntityView view, EntityRecord entity) {
    entity.getAttributes().forEach(
        (key, value) -> {
          if (io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.flattenEnabled(key)) {
            view.getFlattened().put(key, value);
          }
        });
  }

  /** Basic pass-through: all fields map by name. */
  EntityView toView(EntityRecord entity);

  /** MapStruct-generated mapping; post-mapping enriches children + flattening. */
  @Mapping(target = "children", ignore = true)
  EntityDetailView toDetailView(EntityRecord entity, Page<EntitySummary> children);

  /** Children + flattening applied after MapStruct generates the structural mapping. */
  @AfterMapping
  default void enrichDetailView(
      EntityRecord entity, Page<EntitySummary> children, @MappingTarget EntityDetailView view) {
    view.setId(entity.getId());
    view.setEntityType(entity.getEntityType());
    view.setParentId(entity.getParentId());
    view.setOwnerId(entity.getOwnerId());
    view.setName(entity.getName());
    view.setDescription(entity.getDescription());
    view.setStatus(entity.getStatus());
    view.setTags(List.of(entity.getTags()));
    view.setLocation(toLocation(entity.getLocation()));
    view.setCreatedAt(entity.getCreatedAt());
    view.setUpdatedAt(entity.getUpdatedAt());

    Map<String, Object> attrs = new LinkedHashMap<>(entity.getAttributes());
    view.getAttributes().clear();
    view.getAttributes().putAll(attrs);
    attrs.forEach(
        (key, value) -> {
          if (io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.flattenEnabled(key)) {
            view.getFlattened().put(key, value);
          }
        });

    view.setChildren(children);
  }

  /** Lightweight projection for pickers / "far side" of relationships. */
  EntitySummary toSummary(EntityRecord entity);

  // ── request → entity (constructor-level mapping) ──────────────

  @Mapping(target = "id", ignore = true)
  @Mapping(target = "createdAt", ignore = true)
  @Mapping(target = "updatedAt", ignore = true)
  @Mapping(target = "entityType",
      expression = "java(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.trim(req.getEntityType()))")
  @Mapping(target = "name",
      expression = "java(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.trim(req.getName()))")
  @Mapping(target = "status",
      expression = "java(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.normalizeStatus(req.getStatus()))")
  @Mapping(target = "tags",
      expression = "java(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.normalizeTags(req.getTags()))")
  @Mapping(target = "location",
      expression = "java(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.createPoint(req.getLocation()))")
  @Mapping(target = "attributes",
      expression = "java(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.mergeAttributes(req))")
  EntityRecord toEntity(EntityWriteRequest req);

  /** Build a fresh entity record from a create payload. */
  default EntityRecord newEntity(EntityWriteRequest req) {
    return toEntity(req);
  }

  /** Full replacement (PUT): overwrite every writable field on an existing record. */
  default void applyReplace(EntityRecord entity, EntityWriteRequest req) {
    EntityRecord mapped = toEntity(req);
    entity.setEntityType(mapped.getEntityType());
    entity.setName(mapped.getName());
    entity.setDescription(mapped.getDescription());
    entity.setStatus(mapped.getStatus());
    entity.setTags(mapped.getTags());
    entity.setLocation(mapped.getLocation());
    entity.setParentId(mapped.getParentId());
    entity.setOwnerId(mapped.getOwnerId());
    Map<String, Object> attrs = mapped.getAttributes();
    if (!attrs.isEmpty()) {
      entity.getAttributes().clear();
      entity.getAttributes().putAll(attrs);
    }
  }

  /** Partial update (PATCH): null / blank fields are silently skipped. */
  default void applyPatch(EntityRecord entity, EntityWriteRequest req) {
    if (isPresent(req.getEntityType())) {
      entity.setEntityType(req.getEntityType().trim());
    }
    if (isPresent(req.getName())) {
      entity.setName(req.getName().trim());
    }
    if (req.getDescription() != null) {
      entity.setDescription(req.getDescription());
    }
    if (isPresent(req.getStatus())) {
      entity.setStatus(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.normalizeStatus(req.getStatus()));
    }
    if (req.getTags() != null && !req.getTags().isEmpty()) {
      entity.setTags(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.normalizeTags(req.getTags()));
    }
    if (req.getLocation() != null) {
      entity.setLocation(io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.createPoint(req.getLocation()));
    }
    if (req.getParentId() != null) {
      entity.setParentId(req.getParentId());
    }
    if (req.getOwnerId() != null) {
      entity.setOwnerId(req.getOwnerId());
    }
    Map<String, Object> merged = io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.mergeAttributes(req);
    if (!merged.isEmpty()) {
      entity.getAttributes().putAll(merged);
    }
  }

  // ── spatial helpers ───────────────────────────────────────────

  /** Point → { lat, lng }. Swaps coordinate order; null stays null. */
  default LocationDto toLocation(Point point) {
    return io.github.paulushcgcj.roadtoarch.spat.util.SpatMapperUtil.createLocationDto(point);
  }

  // ── private utilities ─────────────────────────────────────────

  private boolean isPresent(String value) {
    return value != null && !value.isBlank();
  }
}
